import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createReadStream} from 'node:fs';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {bundle} from '@remotion/bundler';
import {selectComposition,renderMedia,renderStill} from '@remotion/renderer';
import {mix} from './mix.mjs';
import {normalizeScript,scriptLines,validateFilm} from './src/sdk/production.js';
const root=dirname(fileURLToPath(import.meta.url));
const load=async f=>JSON.parse(await readFile(join(root,f),'utf8'));
const hash=async file=>{const h=createHash('sha256');for await(const b of createReadStream(file))h.update(b);return h.digest('hex');};
const design=await load('design.json'),assets=await load('assets.json');
const script=await readFile(join(root,'script.md'),'utf8'),policy=await load('policy.json');
const scriptHash=createHash('sha256').update(normalizeScript(script)).digest('hex');
const invalid=validateFilm(design,scriptLines(script),assets,scriptHash,policy);
if(invalid.length)throw Error(invalid.join('\n'));
await mkdir(join(root,'build/temp'),{recursive:true});await mkdir(join(root,'output'),{recursive:true});
process.env.TEMP=process.env.TMP=join(root,'build/temp');
for(const a of assets)if(await hash(join(root,'public',a.local))!==a.sha256)throw Error(`Asset changed: ${a.id}`);
const audio=await mix(root,design,assets);
const serveUrl=await bundle({entryPoint:join(root,'src/index.tsx'),publicDir:join(root,'public'),outDir:join(root,'build/bundle')});
const options={serveUrl,logLevel:'error',timeoutInMilliseconds:120000,chromiumOptions:{gl:'angle'}};
const composition=await selectComposition({...options,id:'Spatial-Imagery'});
const stillFrames=[...new Set(design.shots.flatMap(s=>[s.from,Math.floor((s.from+s.to)/2),s.to-1]))];
for(const frame of stillFrames)await renderStill({...options,composition,frame,output:join(root,`output/frame-${frame}.png`)});
const output=join(root,'output/final.mp4');
await renderMedia({...options,composition,codec:'h264',colorSpace:'bt709',crf:18,x264Preset:'fast',concurrency:2,outputLocation:output,onProgress:p=>writeFile(join(root,'build/progress.json'),JSON.stringify({renderedFrames:p.renderedFrames,progress:p.progress})).catch(()=>{})});
const ffprobe=spawnSync(process.env.FFPROBE_BIN??'ffprobe',['-v','error','-count_frames','-show_streams','-show_format','-of','json',output],{encoding:'utf8'});
if(ffprobe.error||ffprobe.status!==0)throw Error('ffprobe failed');
const probe=JSON.parse(ffprobe.stdout),v=probe.streams.find(s=>s.codec_type==='video'),a=probe.streams.find(s=>s.codec_type==='audio'),duration=design.durationInFrames/design.fps;
const issues=[];
if(!v||Number(v.nb_read_frames)!==design.durationInFrames||v.width!==design.width||v.height!==design.height||Math.abs(Number(v.duration)-duration)>2/design.fps)issues.push('Video dimensions, duration or decoded frame count mismatch');
const [num,den]=(v?.avg_frame_rate??'0/1').split('/').map(Number);if(Math.abs(num/den-design.fps)>.001)issues.push('FPS mismatch');
if(audio.audio&&(!a||Math.abs(Number(a.duration)-duration)>2/design.fps))issues.push('Audio duration mismatch');
const decode=spawnSync(process.env.FFMPEG_BIN??'ffmpeg',['-v','error','-i',output,'-f','null','-'],{encoding:'utf8'});if(decode.error||decode.status!==0||decode.stderr.trim())issues.push('Full decode failed');
const evidence={file:'final.mp4',sha256:await hash(output),scriptSha256:await hash(join(root,'script.md')),designSha256:await hash(join(root,'design.json')),compositionSha256:await hash(join(root,'src/index.tsx')),technicalPassed:!issues.length,issues,frames:design.durationInFrames,seconds:duration,width:design.width,height:design.height,audio,stills:stillFrames,review:{normalSpeed:'unverified',listening:'unverified',aesthetic:'unreviewed'}};
await writeFile(join(root,'output/qa.json'),JSON.stringify(evidence,null,2));
if(issues.length)throw Error(issues.join('; '));
console.log(JSON.stringify({video:output,technicalPassed:true,review:'Visual and listening review still required'}));
